# Generated by Django 2.1.1 on 2018-10-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_mail', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=20)),
                ('user_first_name', models.CharField(max_length=20)),
                ('user_last_name', models.CharField(max_length=20)),
                ('user_age', models.IntegerField()),
            ],
        ),
    ]
