# Generated by Django 2.1.1 on 2018-11-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_age',
            new_name='user_born',
        ),
        migrations.AddField(
            model_name='user',
            name='user_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_worker',
            field=models.BooleanField(default=False),
        ),
    ]
