# Generated by Django 2.1.1 on 2018-11-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
