# Generated by Django 2.1.1 on 2018-11-09 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181109_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('vacancy_type', models.CharField(max_length=20)),
                ('vacancy_city', models.CharField(max_length=30)),
                ('vacancy_neighborhood', models.CharField(max_length=50)),
                ('vacancy_adress', models.CharField(max_length=50)),
                ('vacancy_has_smokers', models.BooleanField(default=False)),
                ('vacancy_has_students', models.BooleanField(default=False)),
                ('vacancy_has_workers', models.BooleanField(default=False)),
                ('vacancy_has_animals', models.BooleanField(default=False)),
                ('vacancy_animals_type', models.CharField(max_length=30)),
                ('vacancy_path_photos', models.CharField(max_length=20)),
                ('vacancy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User')),
            ],
        ),
    ]
